[phases.setup]
nixPkgs = ["php84", "php84Packages.composer"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction"
]

[start]
cmd = "php -d error_reporting='E_ALL & ~E_DEPRECATED & ~E_STRICT' -d display_errors=0 -d log_errors=1 -S 0.0.0.0:$PORT -t ."

